Dare Mod
ginglis13/shortstop pull request #36
Opened 2020-02-03 07:03 UTC by brennenhogan

2020-02-03 20:44 UTC, ginglis13 requested changes
looks good yo. i requested some changes. also, could you delete the .DS_Store file from this branch? I forgot to add those to the .gitignore, that's just a folder formatting file on macOS.

One other thing - could you update `app.py` to include this module?

2020-02-03 20:44 UTC, ginglis13 commented on modules/tethics_dare.py
> +        #dare = 'drink piss'
can this get yeeted out

2020-02-03 20:44 UTC, ginglis13 commented on modules/tethics_dare.py
> +	#with open('/Users/brennen/School/Junior Year/shortstoploc/dares.txt') as f:
also this

2020-02-04 00:46 UTC, ginglis13 requested changes

2020-02-04 00:46 UTC, ginglis13 commented on modules/tethics_dare.py
> +    """Detain a user"""
i guess this could be like "dare a user to do something during tethics"

2020-02-04 04:02 UTC, brennenhogan commented
changes complete

2020-02-04 04:41 UTC, ginglis13 approved these changes
good stuff o7

2020-02-04 04:41 UTC, merged